<?php
// $id$

/**
 * @file
 *   Test module for Menu Node API hooks.
 */

/**
 * Store static variables to indicate that hooks fired.
 */
function menu_node_test_set($value = NULL) {
  static $storage;
  if (is_null($value) && isset($storage)) {
    return $storage;
  }
  $storage = $value;
}

/**
 * Get the static value.
 */
function menu_node_test_get() {
  return menu_node_test_set();
}

/**
 * Implements hook_menu_node_insert().
 */
function menu_node_test_menu_node_insert($link, $node) {
  static $i;
  if (!empty($link) && !empty($node)) {
    $i++;
    menu_node_test_set($i);
  }
}

/**
 * Implements hook_menu_node_delete().
 */
function menu_node_test_menu_node_delete($link, $node) {
  if (!empty($link) && !empty($node)) {
    menu_node_test_set('delete');
  }
}
